### ISSUE TITLE
[Feature Request] All Primary Colors

### ISSUE THREAD

**Issue by OdinVex** [suchmememanyskill/Steam-Deck-Themes#1]
A 'Colored Toggle' for each primary color would be nice: Red, Orange, Yellow, Green, Blue, Purple/Indigo, Gray, Inverse (White/Black or Black/White) et cetera.

**Comment by OdinVex** [comment]
@suchmememanyskill, Thank you. I already went through the effort to add all the themes, I was going to git-clone your repo and do a PR. I'll check this repo out. :)

**Comment by suchmememanyskill** [comment]
Sure, thanks :)

**Comment by joamjoamjoam** [comment]
Are these toggle colors going to make it into the theme? If not would you accept a pull request with some more colors?

**Comment by suchmememanyskill** [comment]
Implemented
