### ISSUE TITLE
Compatibility patch for HLTB and Clean Gameview

### ISSUE THREAD

**Issue by lyndonguitar** [suchmememanyskill/Steam-Deck-Themes#10]
Currently when you add HLTB (How long to beat) Decky Plugin, it slightly shifts the Clean Gameview sizing, and lowers down the "Play button" a bit, showing a bit of bug.

HLTB is a very useful tool, along with Clean Gameview making things neater. It would be nice to have compatibility for both.

**Comment by suchmememanyskill** [comment]
I have discussed this with the dev of HLTB and i think they're rolling out a fix on their end
