### ISSUE TITLE
Open __ Background Button functionless

### ISSUE THREAD

**Issue by ArgentAstra** [suchmememanyskill/Steam-Deck-Themes#14]
No images chosen via the "Open <catagory> Background" option applies that image. Admittedly, a lack of documentation makes it unclear if there's a necessary format, name scheme, resolution, or otherwise.

**Comment by suchmememanyskill** [comment]
Hi, are you specifically talking about the 'Static Background' Theme in this repository, or the documentation of the image picker component as a whole? If the latter, this is the wrong repo for that

- Supported filetypes are [jpg, jpeg, png, webp, avif, gif, svg](https://github.com/suchmememanyskill/SDH-CssLoader/blob/main/src/components/PatchComponent.tsx#L51). Picking something else should result in an error toast
- You can only pick a file inside the ~/homebrew/themes dir. Picking something else will result in an error toast

**Comment by suchmememanyskill** [comment]
So then does it work when you put the images in ~/homebrew/themes ?

If not, please tell me the exact steps you take the reproduce the bug. Name every button you press

**Comment by suchmememanyskill** [comment]
No response given, assuming the issue has been fixed
