### ISSUE TITLE
[More Library Icons] amount is drastically reduced when enabled

### ISSUE THREAD

**Issue by mkikets99** [suchmememanyskill/Steam-Deck-Themes#20]
Because how steam loads library, there is an issue with  selecting a game with dpad/L stick.
Only 4 rows are loaded. 
If use a touch screen it seems like it loads a group of 6 games every time
![photo_2023-03-08_12-35-54](https://user-images.githubusercontent.com/22869811/223690702-cc809151-1fd7-4508-8b61-31d575934a25.jpg)
It may be because of scroll size doesn't changed... (maybe...)

**Comment by suchmememanyskill** [comment]
Duplicate issue of #5
