### ISSUE TITLE
Clean Gameview vs Non-steam games

### ISSUE THREAD

**Issue by unicornsandcandies** [suchmememanyskill/Steam-Deck-Themes#24]
Clean Gameview isn't working on games and programs added from my disk. What's even more curious is that after turning it off and on again, it works properly! It's very annoying honestly to switch this every time I turn on my deck. It requires scrolling through right side menu, then scrolling to CSS addon in decky, then searching for this and then exit, that's why I'm reporting this. It seems like all it needs is a delay in launching or something maybe(?) Because it's working no problem after this, it's only acting weird specifaclly on first start, on non-steam games

**Comment by suchmememanyskill** [comment]
Steps to reproduce? I haven't seen this behaviour, even on non-steam games

**Comment by unicornsandcandies** [comment]
> Steps to reproduce? I haven't seen this behaviour, even on non-steam games

If that's okay, I've recorded a video for you. Sorry if that's not okay, just wanted to show you exactly how this issue works

https://youtu.be/d4RIxJqXQ0A

**Comment by suchmememanyskill** [comment]
What steamos branch are you on? What version of clean gameview do you have installed?

**Comment by unicornsandcandies** [comment]
> What steamos branch are you on? What version of clean gameview do you have installed?
> 
> I'm currently on steamos preview (latest) and i cannot reproduce this

Steam os branch stable
Clean gameview 1.2

**Comment by suchmememanyskill** [comment]
Cannot reproduce on steamos stable with steam version 1679680416 with clean gameview v1.2

**Comment by unicornsandcandies** [comment]
> Cannot reproduce on steamos stable with steam version 1679680416 with clean gameview v1.2
> 
> Can you create a preset and send me that preset? (Themes and presets are stored in ~/homebrew/themes. Please zip the preset up and send it here)

[themes.zip](https://github.com/suchmememanyskill/Steam-Deck-Themes/files/11224589/themes.zip)

**Comment by unicornsandcandies** [comment]
> The theme "Large Headers for 3rd Party Apps" seems to be overriding clean gameview. Unsure if it's my issue

It seems to work now. I've disabled it. Thank you so much. Sorry I couldn't guess what's the issue, I'm not sure how to check if themes are incompatible with themselves. Thank you so much for help. For me personally it's solved now because I need clean gameview much more. But if there will be any way I could help solve this I'll gladly send any logs and files necessary. Thank you.
