### ISSUE TITLE
Missing spots for Colored Toggles 

### ISSUE THREAD

**Issue by pparmy** [suchmememanyskill/Steam-Deck-Themes#32]
When launching a game and clicking the Steam Button, the inner menu for "Resume game, controller settings" - and so forth have a few spots where the menu is still the original Steam Deck blue

edit: also I believe the confirmation menu for closing a game is the Steam blue as well

**Comment by pparmy** [comment]
![image](https://github.com/suchmememanyskill/Steam-Deck-Themes/assets/116443069/a53a52cc-e544-41cd-b5c6-8941231882b7)

**Comment by suchmememanyskill** [comment]
Should be fixed by now
