### ISSUE TITLE
Material You: Broken volume menu

### ISSUE THREAD

**Issue by jh-devv** [suchmememanyskill/Steam-Deck-Themes#38]
The volume menu coloring is a bit broken :3
It basically shows the transparent part over the non transparent.

I can send screenshots if needed

*jh-devv*

**Comment by suchmememanyskill** [comment]
That would help, yes. Which theme is this issue for?

**Comment by jh-devv** [comment]
> That would help, yes. Which theme is this issue for?

It's for the Material theme, sorry about not saying that :3

**Comment by suchmememanyskill** [comment]
![image](https://github.com/suchmememanyskill/Steam-Deck-Themes/assets/38142618/974d79aa-1f2d-4dc9-b9b1-153ace94a0c6)

What's broken about this?

**Comment by jh-devv** [comment]
Weird, it seems to be an issue with my setup then!

**Comment by suchmememanyskill** [comment]
Note i did commit some fixes to this repository that are unreleased, please re-test with the latest changes

**Comment by jh-devv** [comment]
Ok! Good
