### ISSUE TITLE
Repo overhaul

### ISSUE THREAD

**Issue by jh-devv** [suchmememanyskill/Steam-Deck-Themes#39]
Hey!
Could somebody basically overhaul the whole repo? Currently as an example the readme file says this is an test repo.

Incorporating Github CI would also be good!
*I can do that if you want, you can add me push permissions :3*

*jh-devv*

**Comment by suchmememanyskill** [comment]
Absolutely not

**Comment by jh-devv** [comment]
> Absolutely not

? Couldn't the README thing be good?
(About the write permissions, I just said I can help if needed :3 )

**Comment by suchmememanyskill** [comment]
I do hope you realise that asking for write permissions on a repo out of nowhere is incredibly creepy. If you want to contribute, pull requests exist

**Comment by jh-devv** [comment]
> I do hope you realise that asking for write permissions on a repo out of nowhere is incredibly creepy. If you want to contribute, pull requests exist

Yep, I know. I'm sorry about that but I can still help :3

**Comment by jh-devv** [comment]
@suchmememanyskill But hey! Again I'm sorry about the permissions thing. If you could "forgive" me it would be cool. I just wanted to help (maybe bit too fast).

But I really like your projects, this has made my "steam deck experience" hell'a lot better :3

**Comment by jh-devv** [comment]
@suchmememanyskill You can remove this issue if you want?
