### ISSUE TITLE
Add steam cloud indicator back to clean game view

### ISSUE THREAD

**Issue by piebaker** [suchmememanyskill/Steam-Deck-Themes#4]
As far as i can tell clean game view removes the steam cloud indicator entirely. Would be great to get this back on the more details/game info tab

**Comment by suchmememanyskill** [comment]
![1](https://user-images.githubusercontent.com/38142618/187320010-fef6ee07-04b6-4ef6-815a-699dbcd32c62.jpg)
![2](https://user-images.githubusercontent.com/38142618/187320014-d222ed22-a0f6-46ed-9e49-b720f9153082.jpg)
![3](https://user-images.githubusercontent.com/38142618/187320017-dcc20c95-8cb4-468c-a037-08fc29989748.jpg)

What do you think of this?

**Comment by piebaker** [comment]
Yup, those bottom two seem great! Just have it pop-up when it's a problem.

**Comment by suchmememanyskill** [comment]
I (probably) can't only pop it in when it's a problem. What you see here is an additional toggle that always show the steam cloud

Feel free to test this, i've committed the changes

**Comment by piebaker** [comment]
Toggle works as advertised! Would be great to have it dynamic in future, but this works 100%

**Comment by KJDee96** [comment]
On the latest Steam Deck Preview update, Steam Cloud information appears to be offset too far upwards
![image](https://user-images.githubusercontent.com/34279714/201661997-2b6e0961-b679-4bb3-9c85-c1f64aa57188.png)
