### ISSUE TITLE
2023/11/09 Steam Beta breaks Switch Like Home

### ISSUE THREAD

**Issue by AkazaRenn** [suchmememanyskill/Steam-Deck-Themes#47]
https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3780269713955734747

Switch Like Home: half of the friends buttons come up into the screen after the update

**Comment by suchmememanyskill** [comment]
What is broken about No Home Filter

**Comment by suchmememanyskill** [comment]
The switch like home theme is impossible to fix without breaking stable, and vice versa. that's not good

**Comment by AkazaRenn** [comment]
> What is broken about No Home Filter

No Home Filter is fine, sorry that was my mistake. Issue updated.
