### ISSUE TITLE
Clean Gameview doesn't work after SteamOS 3.6.8 Beta update

### ISSUE THREAD

**Issue by Sythog** [suchmememanyskill/Steam-Deck-Themes#55]
![20240719_005249](https://github.com/user-attachments/assets/0c33a8ec-421a-4837-b805-0a18beeb5c3e)
Tried to disable the rest of the themes and then apply the Clean Gameview. Didn't help.

SteamOS 3.6.8 Beta
Decky 3.0.0-pre5

**Comment by AFreshSalad** [comment]
Can concur with this, same beta builds for SteamOS and Decky.

**Comment by Kar0ll0** [comment]
Same issue

**Comment by suchmememanyskill** [comment]
Fixed by updating cssloader mappings
