### ISSUE TITLE
Clean Gameview conflicting text

### ISSUE THREAD

**Issue by piebaker** [suchmememanyskill/Steam-Deck-Themes#6]
Looks like the `starting launch` text conflicts with the last played/hours played bar, would be great to have that bar disappear like vanilla behaviour. Screenshot to issue linked
[Link here](https://steamcommunity.com/sharedfiles/filedetails/?id=2856662995)

**Comment by suchmememanyskill** [comment]
Just pushed a commit to resolve this. Can you test it?

**Comment by piebaker** [comment]
Works like a charm! Cheers for fixing it so quick
